Universal functions can be used to do different operations on nd-array liike reducing, accumulating, adding, etc

In [16]:
import numpy as np

In [17]:
# Adding matrix values
a = np.array([[4, 5, 6, 7], [3, 5, 6, 3]])
b = np.array([[14, 15, 16, 17], [13, 51, 16, 31]])
c = np.add(a, b)
print(c)

[[18 20 22 24]
 [16 56 22 34]]


In [23]:
# Creating functions
def f00(a, b):
  return a + b

a = np.array([[4, 5, 6, 7], [3, 5, 6, 3]])
b = np.array([[14, 15, 16, 17], [13, 51, 16, 31]])
c = np.frompyfunc(f00, 2, 1)

In [29]:
# Subtraction
a = np.array([[4, 5, 6, 7], [3, 5, 6, 3]])
b = np.array([[14, 15, 16, 17], [13, 51, 16, 31]])
print(np.subtract(a, b))

# Multiplication
print()
print(np.multiply(a, b))

# Division
print()
print(np.divide(b, a))

# Power
print()
print(np.power(a, 2))

# Remainder
print()
print(np.mod(a, 2))

[[-10 -10 -10 -10]
 [-10 -46 -10 -28]]

[[ 56  75  96 119]
 [ 39 255  96  93]]

[[ 3.5         3.          2.66666667  2.42857143]
 [ 4.33333333 10.2         2.66666667 10.33333333]]

[[16 25 36 49]
 [ 9 25 36  9]]

[[0 1 0 1]
 [1 1 0 1]]


In [31]:
# Quotient and mode
print(np.divmod(a, 2))

# Absolute value
print()
print(np.absolute(np.subtract(a, b)))

(array([[2, 2, 3, 3],
       [1, 2, 3, 1]]), array([[0, 1, 0, 1],
       [1, 1, 0, 1]]))

[[10 10 10 10]
 [10 46 10 28]]


In [35]:
# Rounding decimals
x = np.array([3.44324, 5.09087, -3.756])
print(np.trunc(x))
print(np.fix(x))
print(np.around(x, 2))
print(np.ceil(x))
print(np.floor(x))

[ 3.  5. -3.]
[ 3.  5. -3.]
[ 3.44  5.09 -3.76]
[ 4.  6. -3.]
[ 3.  5. -4.]


In [48]:
# Total summation
print(np.sum([a, b]))

# Summation over an axis
print()
print(a)
print(b)
print(np.sum([a, b], axis=1))

# Cumulative sum
print()
print(np.cumsum([a, b]))

212

[[4 5 6 7]
 [3 5 6 3]]
[[14 15 16 17]
 [13 51 16 31]]
[[ 7 10 12 10]
 [27 66 32 48]]

[  4   9  15  22  25  30  36  39  53  68  84 101 114 165 181 212]


In [51]:
# Product, product over an axis and cumulative product
print(np.product([a, b]))
print(np.product([a, b], axis=1))
print(np.cumprod([a, b]))

4260165331968000
[[ 12  25  36  21]
 [182 765 256 527]]
[               4               20              120              840
             2520            12600            75600           226800
          3175200         47628000        762048000      12954816000
     168412608000    8589043008000  137424688128000 4260165331968000]


In [54]:
# Dicrete difference
print(a)
print()
print(np.diff(a))
print()
print(np.diff(a, n=3))

[[4 5 6 7]
 [3 5 6 3]]

[[ 1  1  1]
 [ 2  1 -3]]

[[ 0]
 [-3]]


In [58]:
# LCM using numpy
print(np.lcm(3, 4))
print(np.lcm.reduce(a))
print(np.lcm.reduce(np.array([1, 4, 23, 45])))

12
[12  5  6 21]
4140


In [67]:
# GCD Greatest common denominator
print(np.gcd.reduce(np.array([12, 24, 30, 42])))
print(np.gcd(24, 12))

6
12


In [82]:
# Set functions
w = np.array([1, 45, 1, 4, 3, 15, 2, 5])
u = np.array([23, 45, 12, 56, 56])
print(np.unique(w))
print(np.union1d(u, w))
print(np.intersect1d(u, w))
print(np.setdiff1d(w, u))
print(np.setxor1d(w, u))

[ 1  2  3  4  5 15 45]
[ 1  2  3  4  5 12 15 23 45 56]
[45]
[ 1  2  3  4  5 15]
[ 1  2  3  4  5 12 15 23 56]
